# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
# highlighter:      rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            PROGENy
tagline:          Tagline for website
description:      "Short description of the tool, for the sidebar"
#url:              https://github.com/christianholland/PROGENy
baseurl:          /PROGENy/
toollogo:         /PROGENy/tool_logo.png

author:
  name:           'Michael Schubert'

paginate:         5

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/christianholland/PROGENy
